"""GPU-backed 3D scalar-field rendering."""

from .mesh import (
    CameraConfig,
    MarkerSpec,
    MeshData,
    SceneStats,
    build_hud_lines,
    build_marker_specs,
    build_mesh_data,
    camera_config_from_preset,
    compute_camera_distance,
    compute_scene_stats,
    get_ground_plane_z,
    normalize_for_colormap,
    sample_display_z_nearest,
)
from .payload import (
    BACKENDS,
    CAMERA_PRESETS,
    GROUND_PLANE_MODES,
    SCALE_MODES,
    BackendName,
    CameraPreset,
    GroundPlaneMode,
    ScaleMode,
    Surface3DConfig,
    SurfacePayload,
    payload_from_analysis_result,
    prepare_z_for_display,
)
from .viewer import (
    RendererError,
    ViewerProcess,
    VispySurfaceRenderer,
    launch_3d_viewer,
    launch_viewer_subprocess,
    show_surface_3d,
)

__all__ = [
    "BACKENDS",
    "CAMERA_PRESETS",
    "GROUND_PLANE_MODES",
    "SCALE_MODES",
    "BackendName",
    "CameraConfig",
    "CameraPreset",
    "GroundPlaneMode",
    "MarkerSpec",
    "MeshData",
    "RendererError",
    "ScaleMode",
    "SceneStats",
    "Surface3DConfig",
    "SurfacePayload",
    "ViewerProcess",
    "VispySurfaceRenderer",
    "build_hud_lines",
    "build_marker_specs",
    "build_mesh_data",
    "camera_config_from_preset",
    "compute_camera_distance",
    "compute_scene_stats",
    "get_ground_plane_z",
    "launch_3d_viewer",
    "launch_viewer_subprocess",
    "normalize_for_colormap",
    "payload_from_analysis_result",
    "prepare_z_for_display",
    "sample_display_z_nearest",
    "show_surface_3d",
]
